### PR TITLE
Update the track documentation

### PR DESCRIPTION
**Pull request by kytrinyx**
This covers in depth some of the challenges of using factor with
exercism, due to exercism's conventions.

Extracted from #6 by @catb0t

### CODE REVIEW

**Comment by catb0t** [comment]
Challenges which will go away when Factor's standard library gets an exercism-sympathetic test wrapper.

**Comment by kytrinyx** [comment]
Niiiiice.

In that case, let's leave this open until we figure out if there will be exercism-friendly vocabulary in the standard library.

**Comment by catb0t** [comment]
Should be closed for the reason I mentioned in #9.

**Comment by kytrinyx** [comment]
Cool, thanks!

**Pull request closed without merging**
