### PR TITLE
Add custom test framework

### PR DESCRIPTION
**Pull request by kytrinyx**
This overcomes the problem of naming mentioned in
https://github.com/exercism/xfactor/issues/5, at least for now.

This also adds helpful information for the people solving problems via
the SETUP.md file, which gets included in each exercise's README.

This is extracted from #6 by @catb0t

### CODE REVIEW

**Comment by kytrinyx** [comment]
Question: the testing framework you've added, is that to verify the exercises as people work on them (in this repository) or is it something that people who are solving exercises will need to download?

**Comment by catb0t** [comment]
The `exercism-testing` code is for contributors and CI (if we ever get a CI that has Factor on it) to verify the example code passes the unit tests. 

The custom framework will go away from this repo and move into Factor's standard lib so that all Factor users have it, as soon as I write the rest of it.

**Comment by catb0t** [comment]
http://github.com/catb0t/exercism.factor

It was rejected from the Factor distribution (rightly so as not applying to a large enough audience), but I guess users will just download that and unzip it to their `factor/work` folder and call it the same way, or download one of the Linux / Windows binaries I'll build and put up there. (Pull requests adding a Mac OSX build will be appreciated).

This should be closed, anyways.

**Comment by kytrinyx** [comment]
That makes sense—it's nice to have the library written, though, even if people have to download it separately.

**Pull request closed without merging**
