### PR TITLE
[WIP] Add hello world exercise

### PR DESCRIPTION
**Pull request by kytrinyx**
This is extracted from #6 by @catb0t and builds on #8.

When #8 has been merged, rebase this onto master, and it should be ready to be merged.

### CODE REVIEW

**Comment by kytrinyx** [comment]
@catb0t Instead of calling the module hello-world, how about calling it just hello or greeting or something? That way we don't have to finangle against the standard library thing.

**Comment by catb0t** [comment]
First of all, thanks for all your work on this, I can't tell you how much I appreciate it. 

> how about calling it just hello or greeting or something?

https://github.com/factor/factor/issues/1639

The folder *has* to be called `hello-world` because the slug, right? Well, the folder name has to match the filenames which gives us the vocabulary name `hello-world`. Unless, we use a `hello` subdirectory of `hello-world` for *this exercise only* which is... weird, and Factor might think I mean `hello-world.hello` instead.

There are a few options for a solution here.

* Make reversing the list of paths where Factor looks for code part of Exercism / Factor setup, **or**
* Make a pull request to add an exercism vocabulary to Factor's standard library, which is a *very* easy thing to do, because the devs are awesome people.

I'm gonna go with the second one in the long run, and then the installation and testing instructions will be *so* much simpler and easier to use. Users will still be using Factor's builtin unit test framework, but they'll be running the tests in a similar way that's sympathetic to Exercism.

**Comment by kytrinyx** [comment]
> The folder has to be called hello-world because the slug, right? Well, the folder name has to match the filenames which gives us the vocabulary name hello-world

Aaaah. Yeah, it does. Oh, wow, I'm sorry the exercism conventions are causing so much trouble!

> Make a pull request to add an exercism vocabulary to Factor's standard library, which is a very easy thing to do, because the devs are awesome people.

Oh, wow. This would be amazing!

**Comment by catb0t** [comment]
> I'm sorry the exercism conventions are causing so much trouble!

It's hardly the fault of Exercism or Factor, it's just the marriage of two frameworks that are both rather strict about names. 

But, the end of the troubles is, because the `exercism.testing` vocabulary is nearly done (next will be a pure-Factor `exercism.client` :) )

**Comment by catb0t** [comment]
Since #8 is gone away, I think this can be safely merged.

**Comment by kytrinyx** [comment]
Cool, thanks!

**Comment by kytrinyx** [comment]
Darn, I screwed that up. #8 was included as part of this one. Would you fix the instructions first as to how someone would run the hello world exercise, and then submit a new pull request with just the hello-world exercise?

**Pull request merged**
